### ISSUE TITLE
The Tour of Remote Browser is actually a prototype?

### ISSUE THREAD

**Issue by 573** [intoli/remote-browser#61]
When I take the "Intoli Remote Browser Tour" i. e. on [page 5](https://intoli.com/tour/5) and click on the Image Data entry within the console after running the example I get the following image which is basically Ok for privacy reasons but nonetheless other than what I would have expected?
![screenshot-2018-4-17 a tour of remote browser - the web extensions api s browser automation framework](https://user-images.githubusercontent.com/123878/38857040-7cff08a4-4228-11e8-9fcd-b0968c82612c.png)

**Comment by prncc** [comment]
That's correct, running a remote-browser script from the tour will actually launch and control a browser instance on a remote server. You're seeing that particular screenshot because the browser that took it happened to have run in San Jose, CA.

**Comment by hbakhtiyor** [comment]
the tour not working, i hit run button several times, nothing happened

**Comment by sangaline** [comment]
@hbakhtiyor Are you still experiencing this issue? It seems to be working when I try it.

**Comment by evildread** [comment]
Test fax
